production:
  host:              <%= node[:clsi][:host] %>
  server_public_dir: <%= node[:clsi][:install_directory] %>/current/public
  cache_dir:         <%= node[:clsi][:install_directory] %>/shared/cache
  latex_chroot_dir:  <%= node[:clsi][:latex_chroot_dir] %>
  latex_compile_dir_relative_to_chroot: <%= node[:clsi][:latex_compile_dir_relative_to_chroot] %>
  latex_compile_dir: <%= node[:clsi][:latex_compile_dir] %>
  latex_command:     <%= node[:clsi][:binaries][:latex] %>
  pdflatex_command:  <%= node[:clsi][:binaries][:pdflatex] %>
  xelatex_command:   <%= node[:clsi][:binaries][:xelatex] %>
  bibtex_command:    <%= node[:clsi][:binaries][:bibtex] %>
  makeindex_command: <%= node[:clsi][:binaries][:makeindex] %>
  dvipdf_command:    <%= node[:clsi][:binaries][:dvipdf] %>
  dvips_command:     <%= node[:clsi][:binaries][:dvips] %>
  compile_timeout:   20
  bibtex_timeout:    10
  dvipdf_timeout:    20
  dvips_timeout:     10
  exception_notification_recipient: errors@examples.com
